services:
  moodle:
    # build:
    #   context: . 
    #   dockerfile: Dockerfile
      # no_cache: true  #Set this only to rebuild from scratch!
    image: renee_edu_platform/moodle-image:1.0
    container_name: moodle-image
    environment:
      MOODLE_USERNAME: moodle_user
      MOODLE_PASSWORD: moodle_password
      MOODLE_EMAIL: admin@admin.com
      MARIADB_HOST: mariadb
      MOODLE_DATABASE_NAME: moodle
      MARIADB_DATABASE: moodle
      MARIADB_PORT_NUMBER: 3306
      MOODLE_WWW_ROOT: vertically-pleasant-sole.ngrok-free.app
      # MOODLE_SSL_PROXY: true
      # MOODLE_REVERSE_PROXY: false
      # VIRTUAL_HOST: vertically-pleasant-sole.ngrok-free.app
      # MARIADB_PORT_NUMBER: 3306
      # MOODLE_DATA_ROOT: /var/www/moodledata
    ports:
      - "80:80"
    volumes:
      # - moodledata:/var/www/moodle
      - moodledata:/var/www/moodledata/
    depends_on:
      - mariadb
  
  mariadb:
    image: mariadb:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MARIADB_CHARACTER_SET: utf8
      MARIADB_COLLATE: utf8_unicode_ci
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - 'mariadb_data:/var/lib/mysql'

  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root

volumes:
  mariadb_data:
  moodledata: 
